name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install lv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Deploy
        run: uv run mkdocs gh-deploy --force
